<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
            background-color: #f4f4f9;
            color: #333;
        }
        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        h1, h2, h3 {
            color: #0056b3;
        }
        ul {
            list-style-type: none;
            padding: 0;
        }
        ul li {
            margin: 5px 0;
        }
        a {
            color: #0056b3;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
        .quote {
            font-style: italic;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Hello, I'm <span>[Mayur Marathe]</span> 👋</h1>
        <p>I am passionate about technology and problem-solving. Here's a glimpse of my work:</p>

        <h2>🛠 Projects</h2>
        <ul>
            <li><strong>Project 1:</strong> To develop an integrated system for hospitals to efficiently manage operations, optimize patient care, and allocate resources.</li>
        </ul>

        <h2>🚀 Skills</h2>
        <ul>
            <li>C++, Python, JavaScript</li>
            <li>Data Structures and Algorithms</li>
            <li>Web Development (React.js, Node.js)</li>
        </ul>

        <h2>🌐 Find Me Online</h2>
        <ul>
            <li><a href="https://github.com/mayuu3/hms.github.io/new/main">GitHub</a></li>
            <li><a href="https://www.linkedin.com/in/mayur-marathe-b9aa742a7/">LinkedIn</a></li>
            <li><a href="https://portfolio.com">Portfolio</a></li>
        </ul>

        <h2>Course Details</h2>
        <p><strong>Course Name:</strong> Algorithms lab</p>
        <p><strong>Course Code:</strong> 24ECSP205</p>
        <p><strong>Name:</strong> Mayur Marathe</p>
        <p><strong>SRN:</strong> 02FE23BCS191</p>
        <p><strong>Course Instructor:</strong> Vaishali Parab</p>
        <p><strong>University:</strong>KLE technological university</p>
        <p><strong>Portfolio Topic/Domain:</strong> Google</p>

        <p class="quote">“The only way to do great work is to love what you do.” – Steve Jobs</p>
    </div>
</body>
</html>
